### ISSUE TITLE
Wordpress always thinks theres a new version even with greater version numbers than the update api

### ISSUE THREAD

**Issue by studioromeo** [jeremyclark13/automatic-theme-plugin-update#1]
Hey nice work on the script!
[This function needs a tweak](https://github.com/jeremyclark13/automatic-theme-plugin-update/blob/master/api/index.php#L172) however to stop wordpress from thinking theres a new version every time.

``` php
if (version_compare($args->version, $latest_package['version'], '<'))
    $update_info->new_version = $update_info->version;

print serialize($update_info);
```

to:

``` php
if (version_compare($args->version, $latest_package['version'], '<')) {
    $update_info->new_version = $update_info->version;
    print serialize($update_info);
}
```

Thanks :)

**Comment by jeremyclark13** [comment]
I see that now with the plugin update check in WP core.  Thanks for pointing that out.  I'll push out a fix for it.
