### ISSUE TITLE
Having a Bit of Trouble - Could you take a Look?

### ISSUE THREAD

**Issue by Schwarttzy** [jeremyclark13/automatic-theme-plugin-update#10]
I could use your help getting the auto update feature to work with a theme I'm developing. Here's a link to the theme with the update file placed in it http://semper-fi.schwarttzy.com/files/2012/08/SemperFi.zip and here is the index.php file I'm using http://semper-fi.schwarttzy.com/files/2012/08/index.zip

Would love to hear what I'm doing wrong, and possibly donate if I starts working.

**Comment by jeremyclark13** [comment]
I'll take a look and see what I can find. I'll report back here what I find.

**Comment by Schwarttzy** [comment]
WOOOT! Thanks so much

**Comment by jeremyclark13** [comment]
Ok there was two problems.  First when requiring the update.php you'll need to use the full path to the file.  Like this:

```
 require(get_template_directory() . '/update.php');
```

Also the api_url was sent wrong in the update.php it has on too many Ts in it.  After correcting those two problems I was able to update to the version you had on the server.  I'm going to go ahead and close this but feel free to open it back up or start another if you have problems.

**Comment by Schwarttzy** [comment]
It definitely works now, just not on my website in any of the sub WordPress (IE: http://test.schwarttzy.com or http://semper-fi.schwarttzy.com/ ). By that I mean that I have a Multi-WordPress install and only on the site the behaves like it is not in the Multi-WordPress install (For Example my home install which is http://schwarttzy.com/ ) still works with the updating.

Hopefully this helps you out with the other ticket I saw that it comes down to some sort of linking problem.

Feel free to close this again.
