### ISSUE TITLE
download.tmp

### ISSUE THREAD

**Issue by ivascumarius** [jeremyclark13/automatic-theme-plugin-update#13]
Hello,

Your code is great, but I encountered a problem.After I do an automatic update, the old theme is deleted and the new updated theme is installed inside a folder called download.tmp. Am I doing something wrong?

Thank you in advanced.

**Comment by ivascumarius** [comment]
I fixed this. It was my error. Great work.

**Comment by lukecarbis** [comment]
How did you fix it?
