### ISSUE TITLE
Theme Info

### ISSUE THREAD

**Issue by gasatrya** [jeremyclark13/automatic-theme-plugin-update#18]
I need to put the changelog.txt in

```
'info' => array(
        'url' => 'http://domain.com/changelog.txt' 
    )
```

But the problem is the iframe in dashboard is too big. Is there any good way to display the theme changelog?

**Comment by turtlepod** [comment]
i don't think you can alter the iframe width, but you can use html, and modify your changelog via css..
make sure to make magin-top around 90px
