### ISSUE TITLE
WordPress 3.3?

### ISSUE THREAD

**Issue by jasonbahl** [jeremyclark13/automatic-theme-plugin-update#2]
There's a chance that I'm just an idiot and missing something, but I've ben trying for a few hours to get this to work and it doesn't appear to work on WordPress 3.3. 

Do you know if there's any issues with this script and WP 3.3?

If it's an issue with WP 3.3 I won't waste more time trying to make it work. . .but if it should be working on WP 3.3, I guess I'll check my details again and make sure I'm not missing any steps or anything like that. 

Thanks,

Jason

**Comment by jeremyclark13** [comment]
Jason,
I haven't had time to fully test this on 3.3 yet, but I'm using code similar to this on a project with 3.3 without problem.  If you'd like to contact me I can help you troubleshoot and get it working.

http://clark-technet.com/contact-me

**Comment by jasonbahl** [comment]
Did you get my message I sent through your website contact form?

Take your time, just wanted to see if the message went through or not. 

Thanks for your assistance. 
- Jason

**Comment by jasonbahl** [comment]
I think I resolved the issue. It was actually an error with my servers php settings. . .

Thanks!

Jason
