### ISSUE TITLE
View version x.x details not showing anything

### ISSUE THREAD

**Issue by ghost** [jeremyclark13/automatic-theme-plugin-update#20]
My plugin shows the update correctly but when clicking on the view version xx details, the information is not populating that popup box
![plugin-updater-1](https://f.cloud.github.com/assets/3625770/167064/bc935392-79c1-11e2-9104-019f8437d690.jpg)

in function check_for_plugin_update the following variables are set at:

$response
stdClass Object ( [version] => 1.1 [date] => 2013-02-18 [author] => Lime Canvas [requires] => 3.0 [tested] => 3.5.1 [homepage] => http://www.limecanvas.com/support-and-maintenance/ [downloaded] => 1 [external] => [package] => https://www.limecanvas.com/download.php?key=579a401b73f2d3cf4af28c1b2d29bdd2 [file_name] => lime-canvas-support-plugin-v1.0.zip [sections] => Array ( [description] => Lime Canvas Support Plugin [installation] => Install, active and enter your Customer ID on the settings page. [screen shots] => na [change log] => na [faq] => na [other notes] => na ) [slug] => test-plugin-update [new_version] => 1.1 ) 

$checked_data
stdClass Object ( [last_checked] => 1361188025 [response] => Array ( [test-plugin-update/test-plugin-update.php] => stdClass Object ( [version] => 1.1 [date] => 2013-02-18 [author] => Lime Canvas [requires] => 3.0 [tested] => 3.5.1 [homepage] => http://www.limecanvas.com/support-and-maintenance/ [downloaded] => 1 [external] => [package] => https://www.limecanvas.com/download.php?key=579a401b73f2d3cf4af28c1b2d29bdd2 [file_name] => lime-canvas-support-plugin-v1.0.zip [sections] => Array ( [description] => Lime Canvas Support Plugin [installation] => Install, active and enter your Customer ID on the settings page. [screen shots] => na [change log] => na [faq] => na [other notes] => na ) [slug] => test-plugin-update [new_version] => 1.1 ) ) ) 

It looks like the correct info is being passed back to the WP updater

Wil.

**Comment by zeropointdevelopment** [comment]
It actually screws up the View Details.. for all other plugins.

Also - when you add more than one plugin to a site using the updater - only one appears in the Updates tab although the numeric counter on the Updates tab says "2".

**Comment by mommaroodles** [comment]
I have mine working perfectly for multiple plugins and on a multisite too - you must be doing something wrong

**Comment by jeremyclark13** [comment]
If you still have the testing code uncommented at the top of the update
code this will happen. Once its commented back out the plugin screens
should go back to normal.

--Jeremy Clark
Clark Tech Services
http://clark-technet.com

**Comment by zeropointdevelopment** [comment]
Thanks for the replies guys.

I created an empty plugin to test this but I just can't get it to show the info or download the new file.

I did re-comment out that testing code Jeremy but it didn't do anything.

Here's the plugin code:
http://pastebin.com/ik2mh64M

and here's the package details:
http://pastebin.com/cUBkQWF8

I have the updater under the /api/ root folder of the remote site

Thanks,
Wil.

**Comment by mommaroodles** [comment]
in your packages.php file - i think you should have the following line:

'package' => 'http://www.limecanvas.com/download.php?key=' . md5('lime-canvas-support-plugin-v1.1.zip' . mktime(0,0,0,date("m"),date("d"),date("Y"))),

AS

'package' => 'http://www.limecanvas.com/api/download.php?key=' . md5('lime-canvas-support-plugin-v1.1.zip' . mktime(0,0,0,date("m"),date("d"),date("Y"))),

your download.php and packages.php + the update folder to add the zip files in - or whatever you've called it should be in the api folder.

**Comment by zeropointdevelopment** [comment]
Thanks @mommaroodles- I'll make that change

**Comment by turtlepod** [comment]
just try to add underscore in all section id:
other notes to other_notes

**Comment by zeropointdevelopment** [comment]
Found the issue - I was wrongly applying the filter
        add_filter('plugins_api', array( &$this, 'lcsup_plugin_api_call', 10, 3 )  );
Should have been
        add_filter('plugins_api', array( &$this, 'lcsup_plugin_api_call'), 10, 3  );

All working now.

Thanks for both of your help.

Awesome code!
