### ISSUE TITLE
Same version keeps prompting for update

### ISSUE THREAD

**Issue by ghost** [jeremyclark13/automatic-theme-plugin-update#21]
Can you think of any reason why the plugin would keep auto updating itself with the same version in the repository?

![plugin-updater-1](https://f.cloud.github.com/assets/3625770/175013/559c25ea-7b35-11e2-92d5-ea47bc866131.jpg)

My plugin version is:
Version: 1.1

My packages are:
http://pastebin.com/rWW981JM

The plugin auto updates but then after an hour or so, appears as an update again.

Wil.

**Comment by mommaroodles** [comment]
why you duplicating the info there? first with version 1.0 then again 1.1? I think if its only 1 plugin, you dont need to ust replace the info with the latest

i think you confusing the script by having 1.0 and 1.1 there lol

**Comment by zeropointdevelopment** [comment]
I thought the idea was that you kept a version history in the $packages variable

**Comment by mommaroodles** [comment]
i'm sure you can keep a version history in the change log or some text file or whatever

**Comment by zeropointdevelopment** [comment]
@mommaroodles - I got rid of the 1.0 version - now the code is only 1.1 but the updater is still asking for an update same as the image above.

http://pastebin.com/aMUuPBxV

**Comment by mommaroodles** [comment]
are you installing the update? and if you are have you changed the version number in the actual plugin itself?

**Comment by zeropointdevelopment** [comment]
Yes to both.  As you can see from the graphic the installed version is 1.1
but the update says the new version is also 1.1

On Thursday, 21 February 2013, Melanie Shepherd wrote:

> are you installing the update? and if you are have you changed the version
> number in the actual plugin itself?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/jeremyclark13/automatic-theme-plugin-update/issues/21#issuecomment-13833942.

## 

Wil Brown

_Lime Canvas_
Web Design & Marketing in Ireland

We ♥ WordPress

wil@limecanvas.com
@LimeCanvas http://tiwtter.com/LimeCanvas

**Comment by mommaroodles** [comment]
and those view lines of code that had to commented out during testing - looks like this

```
//Comment out these two lines during testing.
//if (empty($checked_data->checked))
    //return $checked_data;
```

**Comment by jeremyclark13** [comment]
@mommaroodles Yes this is most likely the cause of the problem.  @limecanvas make sure that all testing code is commented out.

**Comment by zeropointdevelopment** [comment]
In the plugin those two lines are uncommented.

Here's the main plugin code.

http://pastebin.com/39vsjgrY

**Comment by zeropointdevelopment** [comment]
But the comment above it says to comment out the two lines during testing.

Does that not imply to uncommented them in the finished version?

**Comment by zeropointdevelopment** [comment]
When it says "comment out" do you mean uncomment?

**Comment by jeremyclark13** [comment]
No when you are wanting to check for updates at every page load those two lines need to be commented out.  Otherwise in the final version they should be uncommented.  What I was saying was that if those two lines where still commented out it might be causing problems if you still had some of the testing code active but not those two lines commented out.  

But looking over your plugin code I don't think that is the problem.  One thing that helps me diganose problems with this is after this line in the check_for_plugin_update function.

```
$raw_response = wp_remote_post($this->api_url, $request_string);
```

add this

```
var_dump($raw_response);
```

This will dump what the api server responded with.  When I get a minute today I'll take your plugin code and put it on my test server and see if I can replicate this issue.

**Comment by zeropointdevelopment** [comment]
I appreciate you taking the time Jeremy.

The $raw_response dumps this:

```
array(5) { ["headers"]=> array(5) { ["date"]=> string(29) "Thu, 21 Feb 2013 03:16:21 GMT" ["server"]=> string(8) "Apache/2" ["x-powered-by"]=> string(10) "PHP/5.3.10" ["connection"]=> string(5) "close" ["content-type"]=> string(9) "text/html" } ["body"]=> string(1072) "O:8:"stdClass":13:{s:7:"version";s:3:"1.1";s:4:"date";s:10:"2013-02-18";s:6:"author";s:11:"Lime Canvas";s:8:"requires";s:3:"3.0";s:6:"tested";s:5:"3.5.1";s:8:"homepage";s:50:"http://www.limecanvas.com/support-and-maintenance/";s:10:"downloaded";s:1:"1";s:8:"external";s:0:"";s:7:"package";s:79:"http://www.limecanvas.com/api/download.php?key=ee083de47f92850fc2d5fdddd4236110";s:9:"file_name";s:28:"lime-canvas-support-v1.1.zip";s:8:"sections";a:6:{s:11:"description";s:26:"Lime Canvas Support Plugin";s:12:"installation";s:64:"Install, active and enter your Customer ID on the settings page.";s:11:"screenshots";s:3:"n/a";s:9:"changelog";s:97:"
= 1.1 =

* Adds support for Customer ID and current support level
* Auto updates

";s:3:"faq";s:212:"
= Can you hide the dashboard widgets =

Yes. Select "Screen Options" from the top RHS dropdown and uncheck each widget.

We would recommend that you keep the support widget visible at all times.

";s:11:"other_notes";s:3:"n/a";}s:4:"slug";s:19:"lime-canvas-support";s:11:"new_version";s:3:"1.1";}" ["response"]=> array(2) { ["code"]=> int(200) ["message"]=> string(2) "OK" } ["cookies"]=> array(0) { } ["filename"]=> NULL }
```

Or nicely formatted:

```
array(5) { 
["headers"]=> array(5) { 
    ["date"]=> string(29) "Thu, 21 Feb 2013 03:16:21 GMT" 
    ["server"]=> string(8) "Apache/2" 
    ["x-powered-by"]=> string(10) "PHP/5.3.10" 
    ["connection"]=> string(5) "close" 
    ["content-type"]=> string(9) "text/html" } 

["body"]=> string(1072) "O:8:"stdClass":13:{
    s:7:"version";
    s:3:"1.1";
    s:4:"date";
    s:10:"2013-02-18";
    s:6:"author";
    s:11:"Lime Canvas";
    s:8:"requires";
    s:3:"3.0";
    s:6:"tested";
    s:5:"3.5.1";
    s:8:"homepage";
    s:50:"http://www.limecanvas.com/support-and-maintenance/";
    s:10:"downloaded";
    s:1:"1";
    s:8:"external";
    s:0:"";
    s:7:"package";
    s:79:"http://www.limecanvas.com/api/download.php?key=ee083de47f92850fc2d5fdddd4236110";
    s:9:"file_name";
    s:28:"lime-canvas-support-v1.1.zip";
    s:8:"sections";
    a:6:{
        s:11:"description";
        s:26:"Lime Canvas Support Plugin";
        s:12:"installation";
        s:64:"Install, active and enter your Customer ID on the settings page.";
        s:11:"screenshots";
        s:3:"n/a";
        s:9:"changelog";
        s:97:"= 1.1 =
            * Adds support for Customer ID and current support level
            * Auto updates";
        s:3:"faq";
        s:212:"= Can you hide the dashboard widgets =

            Yes. Select "Screen Options" from the top RHS dropdown and uncheck each widget.

            We would recommend that you keep the support widget visible at all times.";
        s:11:"other_notes";
        s:3:"n/a";}
    s:4:"slug";
    s:19:"lime-canvas-support";
    s:11:"new_version";
    s:3:"1.1";}" 

["response"]=> array(2) { 
    ["code"]=> int(200) 
    ["message"]=> string(2) "OK" } 

["cookies"]=> array(0) { } 
    ["filename"]=> NULL }
```

Wil.

**Comment by zeropointdevelopment** [comment]
Did you see anything in the response that would indicate why the plugin is constantly updating?

**Comment by jeremyclark13** [comment]
No that seems fine to me. I'll pull down the plugin code and see if I get the same result on my server.

**Comment by zeropointdevelopment** [comment]
@mommaroodles could you send me your $packages array please so that I can compare?

I just can't figure out why my plugin keeps updating with the same version.

Of course, remove your private info.

Thanks,
Wil.

**Comment by zeropointdevelopment** [comment]
Thanks for both of your time.

I found the error - it was in the plugin where the version was being put together.

I had 
`'version' => $checked_data->checked[$this->plugin_slug .'/'. $test->plugin_slug .'.php'],`

Don't know where the $test object came from but that's what was causing the problem.

I noticed that the version wasn't being set correctly in the request string.
`["request"]=> string(60) "a:2:{s:4:"slug";s:19:"lime-canvas-support";s:7:"version";N;}"`

All is working great now.

Cheerz,
Wil.
