### ISSUE TITLE
404 not found

### ISSUE THREAD

**Issue by ghost** [jeremyclark13/automatic-theme-plugin-update#22]
Hello,

While I testing the plugin in my own server, I don't get any error and plugin works fine. However, when I install the plugin in different server it gives the error. 

$raw_response content:

> Not Found
> The requested URL /update/wp/ was not found on this server.
> Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request.
> Apache/2 Server at screets.com Port 80
> [response] => Array ( [code] => 404 [message] => Not Found ) [cookies] => Array ( ) [filename] => )

How can I solve this issue ?

**Comment by jeremyclark13** [comment]
Are you using the full uri to the server, in the api_url variable.

**Comment by screets** [comment]
Yes, exactly ! Very strange. Here is the my uri:

```
$api_url = 'http://screets.com/update/wp/';
```

**Comment by jeremyclark13** [comment]
Do you have command line access to the server your trying the plugin from.  If so could you verify that the server can resolve the screets.com domain name by pinging it.

**Comment by screets** [comment]
Actually, no. I tried to use exex() function, however it is not allowed for security reasons as well. What should I do ? testing in different servers ?

**Comment by jeremyclark13** [comment]
If you have access to another server, you might want to try it there.

**Comment by screets** [comment]
I have tested with different server and it works fine ! I think i need custom notification for my customers when updating is not possible from their servers.

Thanks.
