### ISSUE TITLE
No Update Detals in the Admin Dashboard

### ISSUE THREAD

**Issue by ghost** [jeremyclark13/automatic-theme-plugin-update#23]
I've got a very simple plugin and added the updating code to it, then updated my packages.

I can see that there is 1 update available in the dashboard but there are no details about the update - nothing to click on to apply the update.

![updater-1](https://f.cloud.github.com/assets/3625770/303355/335fd360-9623-11e2-8ebd-2ecc79f01460.png)

Do you know what would be causing this?

Plugin update code: http://pastebin.com/3gTMHCyR
$packages: http://pastebin.com/aBQhqVk7
print_r($request) : http://pastebin.com/7psALffM

Thanks,
Wil.

**Comment by zeropointdevelopment** [comment]
I found the issue.

My main plugin file was not the same as the slug.

Renamed to the same as the plugin folder and slug and all is well again.

Happy days
