### ISSUE TITLE
domnload.tmp

### ISSUE THREAD

**Issue by lukecarbis** [jeremyclark13/automatic-theme-plugin-update#25]
I'm getting an issue where the file downloads and extracts - Wordpress says it's all good, but it has extracted into a directory called 'download.tmp' instead of the plugin name.

Thoughts?

**Comment by pixedelic** [comment]
same issue... any news?

**Comment by pixedelic** [comment]
Ok... sorry, I simply made a zip file without including the main folder into the zip itself. Fixed.
