### ISSUE TITLE
License information

### ISSUE THREAD

**Issue by sardbaba** [jeremyclark13/automatic-theme-plugin-update#26]
Hi Jeremy,

I'm planning to use your code in a GPL project but you have not specified in what kind of license do you like to release this code.
I forked this repo, but I don't understand what a fork means in terms of license.
Can you help me, please?

**Comment by chriscct7** [comment]
I presume it's WTFPL licensed, based on the exclusion of any mention of GPL.

**Comment by sardbaba** [comment]
LOL are you F kidding me?

**Comment by chriscct7** [comment]
Can't tell if joke or not, but yeah. Its not explicitly GPL for a reason, so that non GPL programs can use it. GPL is not that great of a license. It's very very restrictive. I presume its WTFPL which you can use in GPL programs per the FSF.

**Comment by jeremyclark13** [comment]
Exactly as Chris said no license means your free to use how you'd like. The update part that resides in the theme or plugin will be covered by that license so didn't want it to be restrictive if used in commercial non gpl code. Feel free to use and abuse.

**Comment by sardbaba** [comment]
OK, glad to hear this, thanks. I never heard about WTFPL (and it sounds me like a joke, 'cause it's name).
Never stopping to learn something! ;)

**Comment by chriscct7** [comment]
Not a problem :)
