### ISSUE TITLE
An error occurred while updating...

### ISSUE THREAD

**Issue by wongpk** [jeremyclark13/automatic-theme-plugin-update#27]
I tried to update theme via this plugin, however, some server giving this error:

Downloading update from http://www.domainname.com/updates/download.php?key=26b6d8fec65c87d6af0acc88b274a07a…
Unpacking the update…
Installing the latest version…
Theme update failed.

An error occurred while updating THEME: The package could not be installed. The package contains no files.

I can't be sure why, but this happen on a few server only. Is this anything to do with the server IP being block or something else? I have a few other server that has exact theme, some are working alright.

**Comment by jeremyclark13** [comment]
I've seen this happen before as well with themes from WP.org.  It seems to be more dependent on the server configuration than anything.  One thing to make sure is that the zip file is formatted correctly.  By this I mean that the is a folder with the themes name inside the zip file, not just the contents of the theme.

**Comment by wongpk** [comment]
Hi Jeremy,

Right... Zip file format correctly. Thanks for pointing it out, appreciate your time.
