### ISSUE TITLE
Multiple Plugins

### ISSUE THREAD

**Issue by jasonbahl** [jeremyclark13/automatic-theme-plugin-update#3]
I got this working on one plugin and it's great, but I just tried it on a 2nd plugin and it doesn't seem to work for the 2nd plugin. . .it's pulling in the data from the first plugin. . .

Is there anything special I need to do to have 2 plugins on the same WP Install?

**Comment by jeremyclark13** [comment]
The plugin update file uses some globals, you'll need to prefix all the global variables for each plugin.  I haven't fully tested with multiple versions but I suspect this is the problem.
