### ISSUE TITLE
Cannot modify header information

### ISSUE THREAD

**Issue by Xyolyp** [jeremyclark13/automatic-theme-plugin-update#42]
When I include the Code provided for automatically updating a plugin in my plugin I can't open any link that directly opens a file (like: http://www.domain.com/index.php) because I get 
"Warning: Cannot modify header information - headers already sent by (output started at /www/htdocs/w00ea973/wordpress/wp-content/plugins/myPlugin/myPluginphp:1) in /www/htdocs/w00ea973/wordpress/wp-includes/pluggable.php on line 1207" and it doesn't do anything else. The updating procedure on the other hand works flawless and just the way I want it to work but I can not use your almost perfect code if it breaks almost the entire backend of wordpress. I hope you can help me and I can use your code because it's brilliant.

**Comment by aligos** [comment]
how you fixed this issue?

**Comment by Xyolyp** [comment]
I didn't I scrapped the project and created a Google Home.
