### ISSUE TITLE
Function 'prepare_request' does not exist?

### ISSUE THREAD

**Issue by delightedCrow** [jeremyclark13/automatic-theme-plugin-update#7]
Hi, when I run your plugin code I get an error saying that prepare_request does not exist (https://github.com/jeremyclark13/automatic-theme-plugin-update/blob/master/plugin/test-plugin-update/test-plugin-update.php#L44). I can't find where this function is defined -- is there a php package or class I should have to make this work, or am I just doing something ridiculous? Thanks!

**Comment by jeremyclark13** [comment]
That was my fault I removed that function and updated to use the WordPress equivalent but I forgot to update the check function. I'll get that updated today and pushed back up. Thanks for the report.

**Comment by jeremyclark13** [comment]
Issue fixed with 1.6.2.

**Comment by stass-1** [comment]
Issue back again.

**Comment by jeremyclark13** [comment]
Have you updated the update.php code in your plugin or theme folder with the new version.  I had missed removing the call to the function in a previous version.  But it should be working with the latest version.

**Comment by michaelalhilly** [comment]
It seems update.php still has the prepare_request function. What is the wp equivalent?
