### ISSUE TITLE
Theme update not working with Multisite

### ISSUE THREAD

**Issue by nathanielks** [jeremyclark13/automatic-theme-plugin-update#8]
I developed a theme that uses the update system, and I LOVE it. Thank you for making this. The update system works as expected on a single WordPress install, but when I tested it on multisite, nothing happens. Is this an unfixable limitation imposed by multisite, or would it be possible for it work with multisite as well?

**Comment by jeremyclark13** [comment]
It was working at one time, I haven't tested with the latest versions of multisite.  I'll see what I can figure out.

**Comment by rolandinsh** [comment]
Still no update for multisite? I just started to dig in code, maybe will find issue and will make pull request ;)

And it's working with single install.

**Comment by jeremyclark13** [comment]
It seems to be working for me.  At least with the latest version of multisite.  I've made some other changes that I'm about to commit to the repo and a side effect of that might have been fixing the multisite updates.

**Comment by rolandinsh** [comment]
now works with new update c48e5d1334a91276c5377b80fe0431d7213f7bbb 
thanks!
Based on Your code, made small changes: new parameter `sitehash` to restrict downloads by domain/WordPress and add limit per download rolandinsh/themeupdate@704bdca32b213fac1019d0b5f0bbcc1007df6889
